/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    BpmSelector: typeof import('./src/components/settings/composition/BpmSelector.vue')['default']
    CallAndResponse: typeof import('./src/components/settings/generation/CallAndResponse.vue')['default']
    ChordAdherenceSelector: typeof import('./src/components/settings/chords/ChordAdherenceSelector.vue')['default']
    ChordProgressionBuilder: typeof import('./src/components/settings/chords/ChordProgressionBuilder.vue')['default']
    ChordProgressionDisplay: typeof import('./src/components/settings/chords/ChordProgressionDisplay.vue')['default']
    DiatonicChordPalette: typeof import('./src/components/settings/chords/DiatonicChordPalette.vue')['default']
    EndWithRootNote: typeof import('./src/components/settings/generation/EndWithRootNote.vue')['default']
    EuclideanRhythm: typeof import('./src/components/settings/rhythm/EuclideanRhythm.vue')['default']
    EuclideanVisualizer: typeof import('./src/components/settings/rhythm/EuclideanVisualizer.vue')['default']
    KeySelector: typeof import('./src/components/settings/key_scale/KeySelector.vue')['default']
    LengthSelector: typeof import('./src/components/settings/composition/LengthSelector.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    MelodicContourSelector: typeof import('./src/components/settings/generation/MelodicContourSelector.vue')['default']
    MelodyGenerator: typeof import('./src/components/MelodyGenerator.vue')['default']
    MelodyPlayer: typeof import('./src/components/MelodyPlayer.vue')['default']
    MelodyVisualizer: typeof import('./src/components/MelodyVisualizer.vue')['default']
    MotifRepetition: typeof import('./src/components/settings/generation/MotifRepetition.vue')['default']
    NGramSelector: typeof import('./src/components/settings/generation/NGramSelector.vue')['default']
    OctaveSelector: typeof import('./src/components/settings/composition/OctaveSelector.vue')['default']
    PageFooter: typeof import('./src/components/layout/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
    PredefinedMotif: typeof import('./src/components/settings/generation/PredefinedMotif.vue')['default']
    RestProbabilitySelector: typeof import('./src/components/settings/generation/RestProbabilitySelector.vue')['default']
    RhythmControl: typeof import('./src/components/settings/rhythm/RhythmControl.vue')['default']
    RhythmicLicksSelector: typeof import('./src/components/settings/generation/RhythmicLicksSelector.vue')['default']
    RhythmNotePalette: typeof import('./src/components/settings/rhythm/RhythmNotePalette.vue')['default']
    RhythmPresets: typeof import('./src/components/settings/rhythm/RhythmPresets.vue')['default']
    RhythmSequencer: typeof import('./src/components/settings/rhythm/RhythmSequencer.vue')['default']
    RhythmSequencerControls: typeof import('./src/components/settings/rhythm/RhythmSequencerControls.vue')['default']
    RhythmSequencerGrid: typeof import('./src/components/settings/rhythm/RhythmSequencerGrid.vue')['default']
    RhythmSequencerHelp: typeof import('./src/components/settings/rhythm/RhythmSequencerHelp.vue')['default']
    RhythmSequencerStep: typeof import('./src/components/settings/rhythm/RhythmSequencerStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleSelector: typeof import('./src/components/settings/key_scale/ScaleSelector.vue')['default']
    StartWithRootNote: typeof import('./src/components/settings/generation/StartWithRootNote.vue')['default']
    VelocitySelector: typeof import('./src/components/settings/composition/VelocitySelector.vue')['default']
  }
}
