/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BpmSelector: typeof import('./src/components/BpmSelector.vue')['default']
    Controls: typeof import('./src/components/Controls.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KeySelector: typeof import('./src/components/KeySelector.vue')['default']
    LengthSelector: typeof import('./src/components/LengthSelector.vue')['default']
    MelodyGenerator: typeof import('./src/components/MelodyGenerator.vue')['default']
    MelodyVisualizer: typeof import('./src/components/MelodyVisualizer.vue')['default']
    RhythmEditor: typeof import('./src/components/RhythmEditor.vue')['default']
    ScaleSelector: typeof import('./src/components/ScaleSelector.vue')['default']
  }
}
