export type { Note } from './Note'
export type { Scale } from './Scale'
export type { RhythmPattern } from './Rhythm'
export type { Melody } from './Melody'
export type { Config } from './Config'
export type { Motif } from './motif.models'
